CREATE TABLE IF NOT EXISTS alert_settings (
  user_id BIGINT PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
  high_risk BOOLEAN NOT NULL DEFAULT TRUE,
  news BOOLEAN NOT NULL DEFAULT TRUE,
  monthly_report BOOLEAN NOT NULL DEFAULT TRUE,
  high_threshold INTEGER NOT NULL DEFAULT 70 CHECK (high_threshold BETWEEN 0 AND 100)
);
