-- hs_codes 초기 데이터
-- [1] HS 2단위 챕터 전체(01~97) + [2] 대상 품목 예시 계층(4·6단위)
-- 대상 품목 확정되면 해당 챕터 아래로 4·6·10단위를 확장하면 됨
INSERT INTO hs_codes (hs_code, hs_level, parent_hs_code, name_ko, name_en) VALUES
  ('01',2,NULL,'산 동물','Live animals'),
  ('02',2,NULL,'육류','Meat and edible meat offal'),
  ('03',2,NULL,'어패류','Fish and crustaceans'),
  ('04',2,NULL,'낙농품·란·꿀','Dairy, eggs, honey'),
  ('05',2,NULL,'기타 동물성 생산품','Products of animal origin, nes'),
  ('06',2,NULL,'산 수목·화훼','Live trees and plants'),
  ('07',2,NULL,'채소','Edible vegetables'),
  ('08',2,NULL,'과실·견과','Edible fruit and nuts'),
  ('09',2,NULL,'커피·차·향신료','Coffee, tea, spices'),
  ('10',2,NULL,'곡물','Cereals'),
  ('11',2,NULL,'제분공업 생산품','Milling products, malt, starch'),
  ('12',2,NULL,'채유용 종자','Oil seeds and oleaginous fruits'),
  ('13',2,NULL,'식물성 엑스','Lac, gums, resins'),
  ('14',2,NULL,'기타 식물성 생산품','Vegetable plaiting materials'),
  ('15',2,NULL,'동식물성 유지','Animal/vegetable fats and oils'),
  ('16',2,NULL,'육·어류 조제품','Preparations of meat, fish'),
  ('17',2,NULL,'당류·설탕과자','Sugars and confectionery'),
  ('18',2,NULL,'코코아·초콜릿','Cocoa and cocoa preparations'),
  ('19',2,NULL,'곡물·곡분 조제품','Cereal, flour preparations'),
  ('20',2,NULL,'채소·과실 조제품','Preparations of vegetables, fruit'),
  ('21',2,NULL,'기타 조제 식료품','Miscellaneous edible preparations'),
  ('22',2,NULL,'음료·주류·식초','Beverages, spirits, vinegar'),
  ('23',2,NULL,'식품공업 잔재물·사료','Food industry residues, animal feed'),
  ('24',2,NULL,'담배','Tobacco'),
  ('25',2,NULL,'소금·황·토석류','Salt, sulphur, earths, stone'),
  ('26',2,NULL,'광·슬래그·회','Ores, slag and ash'),
  ('27',2,NULL,'광물성 연료·원유','Mineral fuels, oils'),
  ('28',2,NULL,'무기화학품','Inorganic chemicals'),
  ('29',2,NULL,'유기화학품','Organic chemicals'),
  ('30',2,NULL,'의료용품','Pharmaceutical products'),
  ('31',2,NULL,'비료','Fertilizers'),
  ('32',2,NULL,'염료·안료·페인트','Tanning, dyeing extracts'),
  ('33',2,NULL,'정유·화장품','Essential oils, cosmetics'),
  ('34',2,NULL,'비누·왁스','Soap, waxes'),
  ('35',2,NULL,'단백질계 물질·효소','Albuminoids, glues, enzymes'),
  ('36',2,NULL,'화약류·성냥','Explosives, matches'),
  ('37',2,NULL,'사진용 재료','Photographic goods'),
  ('38',2,NULL,'각종 화학공업 생산품','Miscellaneous chemical products'),
  ('39',2,NULL,'플라스틱','Plastics'),
  ('40',2,NULL,'고무','Rubber'),
  ('41',2,NULL,'원피·가죽','Raw hides and leather'),
  ('42',2,NULL,'가죽제품','Leather articles'),
  ('43',2,NULL,'모피','Furskins'),
  ('44',2,NULL,'목재','Wood and articles of wood'),
  ('45',2,NULL,'코르크','Cork'),
  ('46',2,NULL,'조물 제품','Basketware'),
  ('47',2,NULL,'펄프','Pulp of wood'),
  ('48',2,NULL,'지·판지','Paper and paperboard'),
  ('49',2,NULL,'서적·신문·인쇄물','Printed books, newspapers'),
  ('50',2,NULL,'견','Silk'),
  ('51',2,NULL,'양모','Wool'),
  ('52',2,NULL,'면','Cotton'),
  ('53',2,NULL,'기타 식물성 방직용 섬유','Other vegetable textile fibres'),
  ('54',2,NULL,'인조필라멘트','Man-made filaments'),
  ('55',2,NULL,'인조스테이플섬유','Man-made staple fibres'),
  ('56',2,NULL,'워딩·부직포','Wadding, felt, nonwovens'),
  ('57',2,NULL,'양탄자','Carpets'),
  ('58',2,NULL,'특수직물','Special woven fabrics'),
  ('59',2,NULL,'도포 직물','Coated textile fabrics'),
  ('60',2,NULL,'메리야스 편물','Knitted fabrics'),
  ('61',2,NULL,'의류(편물제)','Apparel, knitted'),
  ('62',2,NULL,'의류(직물제)','Apparel, not knitted'),
  ('63',2,NULL,'기타 방직용 섬유제품','Other made-up textiles'),
  ('64',2,NULL,'신발','Footwear'),
  ('65',2,NULL,'모자','Headgear'),
  ('66',2,NULL,'우산','Umbrellas'),
  ('67',2,NULL,'조제 깃털','Prepared feathers'),
  ('68',2,NULL,'석·시멘트 제품','Articles of stone, cement'),
  ('69',2,NULL,'도자제품','Ceramic products'),
  ('70',2,NULL,'유리','Glass and glassware'),
  ('71',2,NULL,'진주·귀금속','Pearls, precious stones, metals'),
  ('72',2,NULL,'철강','Iron and steel'),
  ('73',2,NULL,'철강제품','Articles of iron or steel'),
  ('74',2,NULL,'구리','Copper'),
  ('75',2,NULL,'니켈','Nickel'),
  ('76',2,NULL,'알루미늄','Aluminium'),
  ('78',2,NULL,'납','Lead'),
  ('79',2,NULL,'아연','Zinc'),
  ('80',2,NULL,'주석','Tin'),
  ('81',2,NULL,'기타 비금속','Other base metals'),
  ('82',2,NULL,'공구·날붙이','Tools, cutlery'),
  ('83',2,NULL,'각종 비금속 제품','Miscellaneous base metal articles'),
  ('84',2,NULL,'기계류','Machinery, mechanical appliances'),
  ('85',2,NULL,'전기기기·전자','Electrical machinery, electronics'),
  ('86',2,NULL,'철도차량','Railway locomotives'),
  ('87',2,NULL,'차량','Vehicles'),
  ('88',2,NULL,'항공기','Aircraft'),
  ('89',2,NULL,'선박','Ships, boats'),
  ('90',2,NULL,'광학·의료기기','Optical, medical instruments'),
  ('91',2,NULL,'시계','Clocks and watches'),
  ('92',2,NULL,'악기','Musical instruments'),
  ('93',2,NULL,'무기','Arms and ammunition'),
  ('94',2,NULL,'가구·침구','Furniture, bedding'),
  ('95',2,NULL,'완구·운동용구','Toys, games, sports'),
  ('96',2,NULL,'잡품','Miscellaneous manufactured articles'),
  ('97',2,NULL,'예술품·골동품','Works of art, antiques'),
  ('0202',4,'02','소고기(냉동)','Meat of bovine animals, frozen'),
  ('020230',6,'0202','냉동 뼈없는 소고기','Bovine cuts boneless, frozen'),
  ('2709',4,'27','원유','Petroleum oils, crude'),
  ('270900',6,'2709','원유','Crude petroleum oils'),
  ('2836',4,'28','탄산염','Carbonates'),
  ('283691',6,'2836','탄산리튬','Lithium carbonates'),
  ('7208',4,'72','열연강판','Flat-rolled iron/steel, hot-rolled'),
  ('720839',6,'7208','열연코일 3mm미만','Hot-rolled coil <3mm'),
  ('8541',4,'85','반도체 소자','Semiconductor devices'),
  ('854142',6,'8541','광전지','Photovoltaic cells'),
  ('8542',4,'85','집적회로(IC)','Electronic integrated circuits'),
  ('854231',6,'8542','프로세서·컨트롤러','Processors and controllers')
ON CONFLICT (hs_code) DO UPDATE SET
  hs_level=EXCLUDED.hs_level, parent_hs_code=EXCLUDED.parent_hs_code,
  name_ko=EXCLUDED.name_ko, name_en=EXCLUDED.name_en;
