-- countries 초기 데이터 (전 세계 249개국, ISO 3166-1)
-- country_code(ISO2,PK) / iso3 / m49(Comtrade) / 한글명 / 영문명 / 권역
INSERT INTO countries (country_code, iso3, m49_code, name_ko, name_en, region) VALUES
  ('AD','AND',20,'안도라','Andorra','유럽'),
  ('AE','ARE',784,'아랍에미리트','United Arab Emirates','아시아'),
  ('AF','AFG',4,'아프가니스탄','Afghanistan','아시아'),
  ('AG','ATG',28,'앤티가 바부다','Antigua and Barbuda','북미'),
  ('AI','AIA',660,'앵귈라','Anguilla','북미'),
  ('AL','ALB',8,'알바니아','Albania','유럽'),
  ('AM','ARM',51,'아르메니아','Armenia','아시아'),
  ('AO','AGO',24,'앙골라','Angola','아프리카'),
  ('AQ','ATA',10,'남극 대륙','Antarctica',''),
  ('AR','ARG',32,'아르헨티나','Argentina','남미'),
  ('AS','ASM',16,'아메리칸 사모아','American Samoa','오세아니아'),
  ('AT','AUT',40,'오스트리아','Austria','유럽'),
  ('AU','AUS',36,'오스트레일리아','Australia','오세아니아'),
  ('AW','ABW',533,'아루바','Aruba','북미'),
  ('AX','ALA',248,'올란드 제도','Åland Islands','유럽'),
  ('AZ','AZE',31,'아제르바이잔','Azerbaijan','아시아'),
  ('BA','BIH',70,'보스니아 헤르체고비나','Bosnia and Herzegovina','유럽'),
  ('BB','BRB',52,'바베이도스','Barbados','북미'),
  ('BD','BGD',50,'방글라데시','Bangladesh','아시아'),
  ('BE','BEL',56,'벨기에','Belgium','유럽'),
  ('BF','BFA',854,'부르키나파소','Burkina Faso','아프리카'),
  ('BG','BGR',100,'불가리아','Bulgaria','유럽'),
  ('BH','BHR',48,'바레인','Bahrain','아시아'),
  ('BI','BDI',108,'부룬디','Burundi','아프리카'),
  ('BJ','BEN',204,'베냉','Benin','아프리카'),
  ('BL','BLM',652,'생바르텔레미','Saint Barthélemy','북미'),
  ('BM','BMU',60,'버뮤다','Bermuda','북미'),
  ('BN','BRN',96,'브루나이','Brunei Darussalam','아시아'),
  ('BO','BOL',68,'볼리비아','Bolivia, Plurinational State of','남미'),
  ('BQ','BES',535,'네덜란드령 카리브','Bonaire, Sint Eustatius and Saba','북미'),
  ('BR','BRA',76,'브라질','Brazil','남미'),
  ('BS','BHS',44,'바하마','Bahamas','북미'),
  ('BT','BTN',64,'부탄','Bhutan','아시아'),
  ('BV','BVT',74,'부베섬','Bouvet Island','남극'),
  ('BW','BWA',72,'보츠와나','Botswana','아프리카'),
  ('BY','BLR',112,'벨라루스','Belarus','유럽'),
  ('BZ','BLZ',84,'벨리즈','Belize','북미'),
  ('CA','CAN',124,'캐나다','Canada','북미'),
  ('CC','CCK',166,'코코스 제도','Cocos (Keeling) Islands','아시아'),
  ('CD','COD',180,'콩고-킨샤사','Congo, The Democratic Republic of the','아프리카'),
  ('CF','CAF',140,'중앙 아프리카 공화국','Central African Republic','아프리카'),
  ('CG','COG',178,'콩고-브라자빌','Congo','아프리카'),
  ('CH','CHE',756,'스위스','Switzerland','유럽'),
  ('CI','CIV',384,'코트디부아르','Côte d''Ivoire','아프리카'),
  ('CK','COK',184,'쿡 제도','Cook Islands','오세아니아'),
  ('CL','CHL',152,'칠레','Chile','남미'),
  ('CM','CMR',120,'카메룬','Cameroon','아프리카'),
  ('CN','CHN',156,'중국','China','아시아'),
  ('CO','COL',170,'콜롬비아','Colombia','남미'),
  ('CR','CRI',188,'코스타리카','Costa Rica','북미'),
  ('CU','CUB',192,'쿠바','Cuba','북미'),
  ('CV','CPV',132,'카보베르데','Cabo Verde','아프리카'),
  ('CW','CUW',531,'퀴라소','Curaçao','북미'),
  ('CX','CXR',162,'크리스마스섬','Christmas Island','아시아'),
  ('CY','CYP',196,'키프로스','Cyprus','아시아'),
  ('CZ','CZE',203,'체코','Czechia','유럽'),
  ('DE','DEU',276,'독일','Germany','유럽'),
  ('DJ','DJI',262,'지부티','Djibouti','아프리카'),
  ('DK','DNK',208,'덴마크','Denmark','유럽'),
  ('DM','DMA',212,'도미니카','Dominica','북미'),
  ('DO','DOM',214,'도미니카 공화국','Dominican Republic','북미'),
  ('DZ','DZA',12,'알제리','Algeria','아프리카'),
  ('EC','ECU',218,'에콰도르','Ecuador','남미'),
  ('EE','EST',233,'에스토니아','Estonia','유럽'),
  ('EG','EGY',818,'이집트','Egypt','아프리카'),
  ('EH','ESH',732,'서사하라','Western Sahara',''),
  ('ER','ERI',232,'에리트리아','Eritrea','아프리카'),
  ('ES','ESP',724,'스페인','Spain','유럽'),
  ('ET','ETH',231,'에티오피아','Ethiopia','아프리카'),
  ('FI','FIN',246,'핀란드','Finland','유럽'),
  ('FJ','FJI',242,'피지','Fiji','오세아니아'),
  ('FK','FLK',238,'포클랜드 제도','Falkland Islands (Malvinas)','남미'),
  ('FM','FSM',583,'미크로네시아','Micronesia, Federated States of','오세아니아'),
  ('FO','FRO',234,'페로 제도','Faroe Islands','유럽'),
  ('FR','FRA',250,'프랑스','France','유럽'),
  ('GA','GAB',266,'가봉','Gabon','아프리카'),
  ('GB','GBR',826,'영국','United Kingdom','유럽'),
  ('GD','GRD',308,'그레나다','Grenada','북미'),
  ('GE','GEO',268,'조지아','Georgia','아시아'),
  ('GF','GUF',254,'프랑스령 기아나','French Guiana','남미'),
  ('GG','GGY',831,'건지','Guernsey','유럽'),
  ('GH','GHA',288,'가나','Ghana','아프리카'),
  ('GI','GIB',292,'지브롤터','Gibraltar','유럽'),
  ('GL','GRL',304,'그린란드','Greenland','북미'),
  ('GM','GMB',270,'감비아','Gambia','아프리카'),
  ('GN','GIN',324,'기니','Guinea','아프리카'),
  ('GP','GLP',312,'과들루프','Guadeloupe','북미'),
  ('GQ','GNQ',226,'적도 기니','Equatorial Guinea','아프리카'),
  ('GR','GRC',300,'그리스','Greece','유럽'),
  ('GS','SGS',239,'사우스조지아 사우스샌드위치 제도','South Georgia and the South Sandwich Islands','남미'),
  ('GT','GTM',320,'과테말라','Guatemala','북미'),
  ('GU','GUM',316,'괌','Guam','오세아니아'),
  ('GW','GNB',624,'기니비사우','Guinea-Bissau','아프리카'),
  ('GY','GUY',328,'가이아나','Guyana','남미'),
  ('HK','HKG',344,'홍콩(중국 특별행정구)','Hong Kong','아시아'),
  ('HM','HMD',334,'허드 맥도널드 제도','Heard Island and McDonald Islands','남극'),
  ('HN','HND',340,'온두라스','Honduras','북미'),
  ('HR','HRV',191,'크로아티아','Croatia','유럽'),
  ('HT','HTI',332,'아이티','Haiti','북미'),
  ('HU','HUN',348,'헝가리','Hungary','유럽'),
  ('ID','IDN',360,'인도네시아','Indonesia','아시아'),
  ('IE','IRL',372,'아일랜드','Ireland','유럽'),
  ('IL','ISR',376,'이스라엘','Israel','아시아'),
  ('IM','IMN',833,'맨 섬','Isle of Man','유럽'),
  ('IN','IND',356,'인도','India','아시아'),
  ('IO','IOT',86,'영국령 인도양 식민지','British Indian Ocean Territory','아시아'),
  ('IQ','IRQ',368,'이라크','Iraq','아시아'),
  ('IR','IRN',364,'이란','Iran, Islamic Republic of','아시아'),
  ('IS','ISL',352,'아이슬란드','Iceland','유럽'),
  ('IT','ITA',380,'이탈리아','Italy','유럽'),
  ('JE','JEY',832,'저지','Jersey','유럽'),
  ('JM','JAM',388,'자메이카','Jamaica','북미'),
  ('JO','JOR',400,'요르단','Jordan','아시아'),
  ('JP','JPN',392,'일본','Japan','아시아'),
  ('KE','KEN',404,'케냐','Kenya','아프리카'),
  ('KG','KGZ',417,'키르기스스탄','Kyrgyzstan','아시아'),
  ('KH','KHM',116,'캄보디아','Cambodia','아시아'),
  ('KI','KIR',296,'키리바시','Kiribati','오세아니아'),
  ('KM','COM',174,'코모로','Comoros','아프리카'),
  ('KN','KNA',659,'세인트키츠 네비스','Saint Kitts and Nevis','북미'),
  ('KP','PRK',408,'북한','Korea, Democratic People''s Republic of','아시아'),
  ('KR','KOR',410,'대한민국','Korea, Republic of','아시아'),
  ('KW','KWT',414,'쿠웨이트','Kuwait','아시아'),
  ('KY','CYM',136,'케이맨 제도','Cayman Islands','북미'),
  ('KZ','KAZ',398,'카자흐스탄','Kazakhstan','아시아'),
  ('LA','LAO',418,'라오스','Lao People''s Democratic Republic','아시아'),
  ('LB','LBN',422,'레바논','Lebanon','아시아'),
  ('LC','LCA',662,'세인트루시아','Saint Lucia','북미'),
  ('LI','LIE',438,'리히텐슈타인','Liechtenstein','유럽'),
  ('LK','LKA',144,'스리랑카','Sri Lanka','아시아'),
  ('LR','LBR',430,'라이베리아','Liberia','아프리카'),
  ('LS','LSO',426,'레소토','Lesotho','아프리카'),
  ('LT','LTU',440,'리투아니아','Lithuania','유럽'),
  ('LU','LUX',442,'룩셈부르크','Luxembourg','유럽'),
  ('LV','LVA',428,'라트비아','Latvia','유럽'),
  ('LY','LBY',434,'리비아','Libya','아프리카'),
  ('MA','MAR',504,'모로코','Morocco','아프리카'),
  ('MC','MCO',492,'모나코','Monaco','유럽'),
  ('MD','MDA',498,'몰도바','Moldova, Republic of','유럽'),
  ('ME','MNE',499,'몬테네그로','Montenegro','유럽'),
  ('MF','MAF',663,'생마르탱','Saint Martin (French part)','북미'),
  ('MG','MDG',450,'마다가스카르','Madagascar','아프리카'),
  ('MH','MHL',584,'마셜 제도','Marshall Islands','오세아니아'),
  ('MK','MKD',807,'북마케도니아','North Macedonia','유럽'),
  ('ML','MLI',466,'말리','Mali','아프리카'),
  ('MM','MMR',104,'미얀마','Myanmar','아시아'),
  ('MN','MNG',496,'몽골','Mongolia','아시아'),
  ('MO','MAC',446,'마카오(중국 특별행정구)','Macao','아시아'),
  ('MP','MNP',580,'북마리아나제도','Northern Mariana Islands','오세아니아'),
  ('MQ','MTQ',474,'마르티니크','Martinique','북미'),
  ('MR','MRT',478,'모리타니','Mauritania','아프리카'),
  ('MS','MSR',500,'몬트세라트','Montserrat','북미'),
  ('MT','MLT',470,'몰타','Malta','유럽'),
  ('MU','MUS',480,'모리셔스','Mauritius','아프리카'),
  ('MV','MDV',462,'몰디브','Maldives','아시아'),
  ('MW','MWI',454,'말라위','Malawi','아프리카'),
  ('MX','MEX',484,'멕시코','Mexico','북미'),
  ('MY','MYS',458,'말레이시아','Malaysia','아시아'),
  ('MZ','MOZ',508,'모잠비크','Mozambique','아프리카'),
  ('NA','NAM',516,'나미비아','Namibia','아프리카'),
  ('NC','NCL',540,'뉴칼레도니아','New Caledonia','오세아니아'),
  ('NE','NER',562,'니제르','Niger','아프리카'),
  ('NF','NFK',574,'노퍽섬','Norfolk Island','오세아니아'),
  ('NG','NGA',566,'나이지리아','Nigeria','아프리카'),
  ('NI','NIC',558,'니카라과','Nicaragua','북미'),
  ('NL','NLD',528,'네덜란드','Netherlands','유럽'),
  ('NO','NOR',578,'노르웨이','Norway','유럽'),
  ('NP','NPL',524,'네팔','Nepal','아시아'),
  ('NR','NRU',520,'나우루','Nauru','오세아니아'),
  ('NU','NIU',570,'니우에','Niue','오세아니아'),
  ('NZ','NZL',554,'뉴질랜드','New Zealand','오세아니아'),
  ('OM','OMN',512,'오만','Oman','아시아'),
  ('PA','PAN',591,'파나마','Panama','북미'),
  ('PE','PER',604,'페루','Peru','남미'),
  ('PF','PYF',258,'프랑스령 폴리네시아','French Polynesia','오세아니아'),
  ('PG','PNG',598,'파푸아뉴기니','Papua New Guinea','오세아니아'),
  ('PH','PHL',608,'필리핀','Philippines','아시아'),
  ('PK','PAK',586,'파키스탄','Pakistan','아시아'),
  ('PL','POL',616,'폴란드','Poland','유럽'),
  ('PM','SPM',666,'생피에르 미클롱','Saint Pierre and Miquelon','북미'),
  ('PN','PCN',612,'핏케언 섬','Pitcairn',''),
  ('PR','PRI',630,'푸에르토리코','Puerto Rico','북미'),
  ('PS','PSE',275,'팔레스타인 지구','Palestine, State of','아시아'),
  ('PT','PRT',620,'포르투갈','Portugal','유럽'),
  ('PW','PLW',585,'팔라우','Palau','오세아니아'),
  ('PY','PRY',600,'파라과이','Paraguay','남미'),
  ('QA','QAT',634,'카타르','Qatar','아시아'),
  ('RE','REU',638,'리유니온','Réunion','아프리카'),
  ('RO','ROU',642,'루마니아','Romania','유럽'),
  ('RS','SRB',688,'세르비아','Serbia','유럽'),
  ('RU','RUS',643,'러시아','Russian Federation','유럽'),
  ('RW','RWA',646,'르완다','Rwanda','아프리카'),
  ('SA','SAU',682,'사우디아라비아','Saudi Arabia','아시아'),
  ('SB','SLB',90,'솔로몬 제도','Solomon Islands','오세아니아'),
  ('SC','SYC',690,'세이셸','Seychelles','아프리카'),
  ('SD','SDN',729,'수단','Sudan','아프리카'),
  ('SE','SWE',752,'스웨덴','Sweden','유럽'),
  ('SG','SGP',702,'싱가포르','Singapore','아시아'),
  ('SH','SHN',654,'세인트헬레나','Saint Helena, Ascension and Tristan da Cunha','아프리카'),
  ('SI','SVN',705,'슬로베니아','Slovenia','유럽'),
  ('SJ','SJM',744,'스발바르제도-얀마웬섬','Svalbard and Jan Mayen','유럽'),
  ('SK','SVK',703,'슬로바키아','Slovakia','유럽'),
  ('SL','SLE',694,'시에라리온','Sierra Leone','아프리카'),
  ('SM','SMR',674,'산마리노','San Marino','유럽'),
  ('SN','SEN',686,'세네갈','Senegal','아프리카'),
  ('SO','SOM',706,'소말리아','Somalia','아프리카'),
  ('SR','SUR',740,'수리남','Suriname','남미'),
  ('SS','SSD',728,'남수단','South Sudan','아프리카'),
  ('ST','STP',678,'상투메 프린시페','Sao Tome and Principe','아프리카'),
  ('SV','SLV',222,'엘살바도르','El Salvador','북미'),
  ('SX','SXM',534,'신트마르턴','Sint Maarten (Dutch part)',''),
  ('SY','SYR',760,'시리아','Syrian Arab Republic','아시아'),
  ('SZ','SWZ',748,'에스와티니','Eswatini','아프리카'),
  ('TC','TCA',796,'터크스 케이커스 제도','Turks and Caicos Islands','북미'),
  ('TD','TCD',148,'차드','Chad','아프리카'),
  ('TF','ATF',260,'프랑스 남부 지방','French Southern Territories',''),
  ('TG','TGO',768,'토고','Togo','아프리카'),
  ('TH','THA',764,'태국','Thailand','아시아'),
  ('TJ','TJK',762,'타지키스탄','Tajikistan','아시아'),
  ('TK','TKL',772,'토켈라우','Tokelau','오세아니아'),
  ('TL','TLS',626,'동티모르','Timor-Leste',''),
  ('TM','TKM',795,'투르크메니스탄','Turkmenistan','아시아'),
  ('TN','TUN',788,'튀니지','Tunisia','아프리카'),
  ('TO','TON',776,'통가','Tonga','오세아니아'),
  ('TR','TUR',792,'터키','Türkiye','아시아'),
  ('TT','TTO',780,'트리니다드 토바고','Trinidad and Tobago','북미'),
  ('TV','TUV',798,'투발루','Tuvalu','오세아니아'),
  ('TW','TWN',158,'대만','Taiwan, Province of China','아시아'),
  ('TZ','TZA',834,'탄자니아','Tanzania, United Republic of','아프리카'),
  ('UA','UKR',804,'우크라이나','Ukraine','유럽'),
  ('UG','UGA',800,'우간다','Uganda','아프리카'),
  ('UM','UMI',581,'미국령 해외 제도','United States Minor Outlying Islands',''),
  ('US','USA',840,'미국','United States','북미'),
  ('UY','URY',858,'우루과이','Uruguay','남미'),
  ('UZ','UZB',860,'우즈베키스탄','Uzbekistan','아시아'),
  ('VA','VAT',336,'바티칸 시국','Holy See (Vatican City State)',''),
  ('VC','VCT',670,'세인트빈센트그레나딘','Saint Vincent and the Grenadines','북미'),
  ('VE','VEN',862,'베네수엘라','Venezuela, Bolivarian Republic of','남미'),
  ('VG','VGB',92,'영국령 버진아일랜드','Virgin Islands, British','북미'),
  ('VI','VIR',850,'미국령 버진아일랜드','Virgin Islands, U.S.','북미'),
  ('VN','VNM',704,'베트남','Viet Nam','아시아'),
  ('VU','VUT',548,'바누아투','Vanuatu','오세아니아'),
  ('WF','WLF',876,'왈리스-푸투나 제도','Wallis and Futuna','오세아니아'),
  ('WS','WSM',882,'사모아','Samoa','오세아니아'),
  ('YE','YEM',887,'예멘','Yemen','아시아'),
  ('YT','MYT',175,'마요트','Mayotte','아프리카'),
  ('ZA','ZAF',710,'남아프리카','South Africa','아프리카'),
  ('ZM','ZMB',894,'잠비아','Zambia','아프리카'),
  ('ZW','ZWE',716,'짐바브웨','Zimbabwe','아프리카')
ON CONFLICT (country_code) DO UPDATE SET
  iso3=EXCLUDED.iso3, m49_code=EXCLUDED.m49_code,
  name_ko=EXCLUDED.name_ko, name_en=EXCLUDED.name_en, region=EXCLUDED.region;
