"use client"

// 추천 공급사의 공개 정보와 실무 검토 항목을 보여주는 공급사 상세 화면입니다.
// 현재 Pilbara Minerals에 고정된 예시이며 추후 공급사 ID 기반 동적 화면으로 전환합니다.

import Link from "next/link"
import { useState } from "react"
import { ArrowLeft, ArrowRight, BadgeCheck, Bell, Building2, Check, CheckCircle2, ClipboardCheck, ExternalLink, FileText, Globe2, MapPin, ShieldCheck, ShieldAlert, Star, Truck } from "lucide-react"
import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"

const scores = [
  ["공급 안정성", 91, "호주 광산 기반 · 장기 계약 검토 가능"],
  ["조달 조건 적합도", 86, "목표 수량 및 납기 조건 부합"],
  ["물류 효율", 80, "부산항 기준 평균 18~23일"],
  ["ESG·인증", 88, "환경 정보 공개 및 책임광물 기준 충족"],
]

export default function SupplierDetailPage() {
  const [saved, setSaved] = useState(false)
  const [candidate, setCandidate] = useState(false)
  return <div className="min-h-screen bg-slate-50 text-slate-900">
    <header className="flex h-16 items-center justify-between border-b border-slate-200 bg-white px-6"><Link href="/dashboard" className="flex items-center gap-2.5"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-blue-600 to-cyan-500 shadow-sm"><ShieldAlert className="h-4 w-4 text-white" /></div><span className="font-semibold tracking-tight">SupplyGuard</span></Link><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="relative"><Bell className="h-4 w-4" /><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-rose-500 ring-2 ring-white" /></Button><Avatar className="h-8 w-8 border border-slate-200"><AvatarFallback className="bg-blue-50 text-xs font-semibold text-blue-700">SW</AvatarFallback></Avatar></div></header>
    <main className="mx-auto max-w-6xl px-5 py-8 md:px-8"><Link href="/recommendations" className="inline-flex items-center gap-1.5 text-sm font-medium text-slate-500 hover:text-blue-600"><ArrowLeft className="h-4 w-4" /> 대체 공급처 추천으로 돌아가기</Link>
      <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row"><div className="flex gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600"><Building2 className="h-7 w-7" /></div><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight">Pilbara Minerals</h1><Badge className="border-blue-100 bg-blue-50 text-blue-700 hover:bg-blue-50"><BadgeCheck className="mr-1 h-3.5 w-3.5" />공개 정보 확인</Badge></div><p className="mt-2 text-sm text-slate-500">호주 · 리튬 광산 개발 및 정광 공급</p><div className="mt-3 flex flex-wrap gap-2"><Badge className="border-slate-100 bg-slate-50 text-slate-600 hover:bg-slate-50">리튬 탄산염</Badge><Badge className="border-slate-100 bg-slate-50 text-slate-600 hover:bg-slate-50">호주 공급망</Badge><Badge className="border-slate-100 bg-slate-50 text-slate-600 hover:bg-slate-50">ESG 정보 공개</Badge></div></div></div><div className="rounded-xl bg-emerald-50 px-4 py-3 text-right"><p className="text-2xl font-semibold text-emerald-600">89</p><p className="text-xs text-emerald-700">조달 적합도</p></div></div><div className="mt-7 flex flex-wrap gap-3 border-t border-slate-100 pt-5"><Button onClick={() => setCandidate(!candidate)} className={candidate ? "bg-blue-600 hover:bg-blue-700" : "bg-slate-900 hover:bg-slate-800"}>{candidate ? <><Check className="mr-2 h-4 w-4" />검토 후보에 추가됨</> : <><Star className="mr-2 h-4 w-4" />검토 후보에 추가</>}</Button><Button onClick={() => setSaved(true)} variant="outline" className="border-slate-200"><ClipboardCheck className="mr-2 h-4 w-4" />{saved ? "저장됨" : "공급사 저장"}</Button><Button variant="ghost" className="text-slate-600">공개 출처 보기 <ExternalLink className="ml-2 h-4 w-4" /></Button></div>{saved && <p className="mt-4 text-sm text-emerald-600"><CheckCircle2 className="mr-1.5 inline h-4 w-4" /> 공급사 후보 목록에 저장했습니다.</p>}</section>
      <div className="mt-6 grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2"><Card className="border-slate-200 shadow-sm"><CardHeader className="pb-3"><CardTitle className="text-base">추천 적합도 분석</CardTitle><CardDescription className="mt-1">리튬 탄산염 조달 조건과 공개 정보를 비교했습니다.</CardDescription></CardHeader><CardContent className="space-y-5">{scores.map(([label, score, note]) => <div key={label as string}><div className="flex items-center justify-between"><div><p className="text-sm font-medium">{label}</p><p className="mt-1 text-xs text-slate-500">{note}</p></div><span className="text-sm font-semibold text-emerald-600">{score}</span></div><Progress value={score as number} className="mt-2 h-2" /></div>)}</CardContent></Card><Card className="border-slate-200 shadow-sm"><CardHeader className="pb-3"><CardTitle className="text-base">공개 기업 정보</CardTitle><CardDescription className="mt-1">공시·기업 공개 자료를 기반으로 정리한 참고 정보입니다.</CardDescription></CardHeader><CardContent className="divide-y divide-slate-100">{[["사업 분야", "리튬 광산 개발 · 정광 공급"], ["본사 소재지", "퍼스, 서호주"], ["주요 생산 거점", "Pilgangoora Operation"], ["공개 데이터 기준", "연간 생산·운영 보고서"]].map(([key, value]) => <div className="flex justify-between gap-5 py-3 text-sm" key={key}><span className="text-slate-500">{key}</span><span className="text-right font-medium">{value}</span></div>)}</CardContent></Card></div><aside className="space-y-6"><Card className="border-blue-100 bg-gradient-to-br from-blue-50 to-cyan-50 shadow-sm"><CardHeader className="pb-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-blue-600 text-white"><ShieldCheck className="h-4 w-4" /></div><CardTitle className="mt-3 text-base">추천 이유</CardTitle></CardHeader><CardContent className="space-y-4"><Reason icon={Globe2} title="낮은 국가 위험" text="호주는 지정학·수출 규제 위험이 상대적으로 낮습니다." /><Reason icon={Truck} title="안정적인 공급 경로" text="정기 선적과 운영 정보 확인이 가능한 공급망입니다." /><Reason icon={MapPin} title="다변화 효과" text="중국 의존도를 낮추는 1순위 후보입니다." /></CardContent></Card><Card className="border-slate-200 shadow-sm"><CardHeader className="pb-3"><CardTitle className="text-base">검토 전 확인 사항</CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-slate-600"><CheckItem text="최소 주문 수량(MOQ) 확인" /><CheckItem text="정제·가공 단계 공급 가능 여부" /><CheckItem text="납기·인코텀즈 조건 협의" /><CheckItem text="샘플 및 품질 인증 검토" /><Button asChild className="mt-2 w-full bg-blue-600 hover:bg-blue-700"><Link href="/reports/new">검토 보고서에 추가 <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></CardContent></Card></aside></div>
    </main>
  </div>
}

function Reason({ icon: Icon, title, text }: { icon: typeof Globe2; title: string; text: string }) { return <div className="flex gap-3"><div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-white text-blue-600 shadow-sm"><Icon className="h-3.5 w-3.5" /></div><div><p className="text-sm font-medium">{title}</p><p className="mt-0.5 text-xs leading-5 text-slate-500">{text}</p></div></div> }
function CheckItem({ text }: { text: string }) { return <div className="flex items-center gap-2"><Check className="h-4 w-4 text-blue-600" /><span>{text}</span></div> }
