"use client"

// 생성된 월간 리튬 공급망 리스크 보고서를 검토하고 공유하는 상세 화면입니다.
// 보고서 내용과 검토 상태는 백엔드 연결 전 사용하는 정적 예시입니다.

import Link from "next/link"
import { useState } from "react"
import { ArrowLeft, Bell, Check, CheckCircle2, ChevronDown, Download, FileText, Mail, PencilLine, Send, ShieldAlert, Sparkles, Users } from "lucide-react"
import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"

const toc = ["경영진 요약", "공급망 리스크 분석", "대체 공급처 제안", "권장 대응 전략"]

export default function ReportDetailPage() {
  const [editing, setEditing] = useState(false)
  const [sharing, setSharing] = useState(false)
  const [sent, setSent] = useState(false)
  const [summary, setSummary] = useState("중국산 리튬 탄산염의 수출 규제 관련 위험이 상승하여 조달 다변화가 필요합니다. 호주는 공급 안정성과 ESG 기준 측면에서 가장 적합한 대체 국가이며, 칠레는 가격 경쟁력 측면에서 병행 검토를 권장합니다.")

  return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="flex h-16 items-center justify-between border-b border-slate-200 bg-white px-6"><Link href="/dashboard" className="flex items-center gap-2.5"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-blue-600 to-cyan-500 shadow-sm"><ShieldAlert className="h-4 w-4 text-white" /></div><span className="font-semibold tracking-tight">SupplyGuard</span></Link><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="relative text-slate-600"><Bell className="h-4 w-4" /><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-rose-500 ring-2 ring-white" /></Button><Avatar className="h-8 w-8 border border-slate-200"><AvatarFallback className="bg-blue-50 text-xs font-semibold text-blue-700">SW</AvatarFallback></Avatar></div></header>
    <main className="mx-auto max-w-7xl px-5 py-8 md:px-8"><Link href="/reports/new" className="inline-flex items-center gap-1.5 text-sm font-medium text-slate-500 hover:text-blue-600"><ArrowLeft className="h-4 w-4" /> 보고서 생성으로 돌아가기</Link><div className="mt-6 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-sm font-medium text-violet-600"><FileText className="h-4 w-4" /> AI 생성 초안</div><h1 className="text-2xl font-semibold tracking-tight md:text-3xl">7월 리튬 탄산염 공급망 리스크 보고서</h1><div className="mt-2 flex flex-wrap items-center gap-2 text-sm text-slate-500"><span>마지막 저장: 방금 전</span><span className="text-slate-300">·</span><Badge className="border-amber-100 bg-amber-50 text-amber-700 hover:bg-amber-50">검토 필요</Badge></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" className="border-slate-200"><Download className="mr-2 h-4 w-4" />PDF 다운로드</Button><Button onClick={() => setSharing(!sharing)} className="bg-blue-600 hover:bg-blue-700"><Mail className="mr-2 h-4 w-4" />사내 공유</Button></div></div>
      {sharing && <Card className="mt-6 border-blue-100 bg-blue-50/70 shadow-sm"><CardContent className="p-5"><div className="flex flex-col gap-5 lg:flex-row lg:items-end"><div className="flex-1"><Label className="text-sm font-medium">수신자 이메일</Label><Input className="mt-2 bg-white" defaultValue="purchasing@company.co.kr, production@company.co.kr" /></div><div className="flex-1"><Label className="text-sm font-medium">공유 메시지</Label><Input className="mt-2 bg-white" defaultValue="7월 리스크 보고서 초안을 검토해 주세요." /></div><Button onClick={() => { setSent(true); setSharing(false) }} className="bg-blue-600 hover:bg-blue-700"><Send className="mr-2 h-4 w-4" />이메일 발송</Button></div></CardContent></Card>}
      {sent && <div className="mt-4 flex items-center gap-2 rounded-lg border border-emerald-100 bg-emerald-50 px-4 py-3 text-sm text-emerald-700"><CheckCircle2 className="h-4 w-4" /> 구매팀과 생산팀에 보고서 초안 링크를 발송했습니다.</div>}
      <div className="mt-6 grid gap-6 xl:grid-cols-4"><aside className="space-y-5 xl:col-span-1"><Card className="border-slate-200 shadow-sm"><CardHeader className="pb-3"><CardTitle className="text-base">보고서 목차</CardTitle></CardHeader><CardContent className="space-y-1">{toc.map((item, index) => <button className={`flex w-full items-center gap-3 rounded-md px-3 py-2 text-left text-sm ${index === 0 ? "bg-violet-50 font-medium text-violet-700" : "text-slate-600 hover:bg-slate-50"}`} key={item}><span className="text-xs text-slate-400">{index + 1}</span>{item}</button>)}</CardContent></Card><Card className="border-slate-200 shadow-sm"><CardHeader className="pb-3"><CardTitle className="text-base">공유 현황</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><Status name="전상욱" role="작성자" done /><Status name="구매팀" role="검토 대기" /><Status name="생산팀" role="검토 대기" /></CardContent></Card></aside>
        <section className="space-y-6 xl:col-span-3"><Card className="border-slate-200 shadow-sm"><CardHeader className="flex flex-row items-center justify-between space-y-0 border-b border-slate-100 pb-5"><div><CardTitle className="text-base">1. 경영진 요약</CardTitle><CardDescription className="mt-1">현재 리스크 상황과 우선 대응 방향</CardDescription></div><Button onClick={() => setEditing(!editing)} variant="outline" size="sm" className="border-slate-200"><PencilLine className="mr-1.5 h-3.5 w-3.5" />{editing ? "저장" : "수정"}</Button></CardHeader><CardContent className="p-6">{editing ? <Textarea value={summary} onChange={(event) => setSummary(event.target.value)} className="min-h-32 resize-none leading-7" /> : <p className="text-sm leading-7 text-slate-600">{summary}</p>}<div className="mt-5 rounded-lg border border-rose-100 bg-rose-50 p-4"><p className="text-sm font-semibold text-rose-700">핵심 판단</p><p className="mt-1 text-sm leading-6 text-rose-700/80">중국 공급 의존도 86%로, 공급국 다변화를 위한 구매 검토를 즉시 시작하는 것이 필요합니다.</p></div></CardContent></Card><div className="grid gap-6 lg:grid-cols-2"><Card className="border-slate-200 shadow-sm"><CardHeader className="pb-3"><CardTitle className="text-base">2. 공급망 리스크 분석</CardTitle></CardHeader><CardContent className="space-y-4"><ReportMetric label="현재 SGRI" value="82 · 고위험" tone="text-rose-600" /><ReportMetric label="주요 위험 요인" value="수출 규제 · 공급국 집중" /><ReportMetric label="관련 뉴스" value="최근 24시간 7건" /></CardContent></Card><Card className="border-slate-200 shadow-sm"><CardHeader className="pb-3"><CardTitle className="text-base">3. 대체 공급처 제안</CardTitle></CardHeader><CardContent className="space-y-4"><ReportMetric label="1순위 대체국" value="호주 · 적합도 82" tone="text-emerald-600" /><ReportMetric label="2순위 대체국" value="칠레 · 적합도 76" /><ReportMetric label="추천 공급사" value="Pilbara Minerals" /></CardContent></Card></div><Card className="border-blue-100 bg-gradient-to-r from-blue-50 to-cyan-50 shadow-sm"><CardContent className="flex flex-col gap-4 p-5 md:flex-row md:items-center"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-blue-600 text-white"><Sparkles className="h-5 w-5" /></div><div className="flex-1"><p className="font-semibold">AI 개선 제안</p><p className="mt-1 text-sm text-slate-600">보고서에 현재 안전재고 일수와 구매 담당자의 검토 일정을 추가하면 실행력이 높아집니다.</p></div><Button variant="outline" className="w-fit border-blue-200 bg-white text-blue-700">제안 반영</Button></CardContent></Card></section>
      </div>
    </main>
  </div>
}

function Status({ name, role, done }: { name: string; role: string; done?: boolean }) { return <div className="flex items-center gap-3"><span className={`flex h-7 w-7 items-center justify-center rounded-full text-xs font-semibold ${done ? "bg-blue-100 text-blue-700" : "bg-slate-100 text-slate-500"}`}>{name.slice(0, 1)}</span><div><p className="text-sm font-medium">{name}</p><p className="text-xs text-slate-500">{role}</p></div>{done && <Check className="ml-auto h-4 w-4 text-blue-600" />}</div> }
function ReportMetric({ label, value, tone = "text-slate-800" }: { label: string; value: string; tone?: string }) { return <div className="flex items-center justify-between border-b border-slate-100 pb-3 text-sm last:border-0 last:pb-0"><span className="text-slate-500">{label}</span><span className={`font-medium ${tone}`}>{value}</span></div> }
